CIRCUITPY_WIFI_SSID = ""
CIRCUITPY_WIFI_PASSWORD = ""
AIO_USERNAME = ""
AIO_KEY = ""
PM10_STANDARD_FEED_NAME = ""
PM25_STANDARD_FEED_NAME = ""
PM100_STANDARD_FEED_NAME = ""
PM10_ENV_FEED_NAME = ""
PM25_ENV_FEED_NAME = ""
PM100_ENV_FEED_NAME = ""
PARTICLES03UM_FEED_NAME = ""
PARTICLES05UM_FEED_NAME = ""
PARTICLES10UM_FEED_NAME = ""
PARTICLES25UM_FEED_NAME = ""
PARTICLES50UM_FEED_NAME = ""
PARTICLES100UM_FEED_NAME = ""
